server:
    port: 8020
spring:
    h2:
        console:
            enabled: true
    jpa:
        database: H2
        show-sql: true
        hibernate:
            format_sql: true
            ddl-auto: create
            naming_strategy: org.hibernate.cfg.ImprovedNamingStrategy